### ISSUE TITLE
Viranomaispäätökset-tasoa ei löydy lokaalissa kehitysversiossa

### ISSUE THREAD

**Issue by Mtk112** [punosmobile/jkr-lahti#105]
Viranomaispäätökset-tasoa ei löydy lokaalissa-kehitys veriossa.
Projektia avatessa tulee virheilmoitus "Handle unavailable layers".
Dev- ja test-kannoilla viranomaispäätökset-taso loytyy.

**Comment by AnniinaMet** [comment]
Ei osata ottaa kantaa onko enää ajankohtainen, muttei aiheuta meille ongelmaa
