### ISSUE TITLE
Lisää taajama-alueiden päivitys wheel-työkalun ohjeeseen

### ISSUE THREAD

**Issue by Mtk112** [punosmobile/jkr-lahti#109]
Lisätään tarvittavat komennot wheel-työkaluun taajama-alueiden päivittämiseksi.

**Comment by ltalve** [comment]
Taajama-alueiden lisäystä ei ole lisätty wheeliin, koska järjestelmä ei toistaiseksi osaa käsitellä taajama-alueiden päättymistä ja uuden alkamista. Myöhemmin, kun taajama-alueen päivitys tulee ajankohtaiseksi, on lisättävä järjestelmään käsittely, jossa aiempi aluerajaus saa päättymispäivämäärän ja uusi alkamispäivämäärän sekä varmistettava, että velvoitetarkistukset käsittelevät nämä voimassaoloajat halutulla tavalla.

Ks. #142

**Comment by AnniinaMet** [comment]
Tämä tulleen ajankohtaiseksi, jos määräyksissä määritelty velvoitealue muuttuu
