### ISSUE TITLE
Päivitä tietomallin dokumentaatio

### ISSUE THREAD

**Issue by ltalve** [punosmobile/jkr-lahti#125]
Tietomallin dokumentaatio käytävä läpi ja päivitettävä taulujen ja kenttien kuvaukset/tietolähteet. Työkaluna voi käyttää esim. https://github.com/k1LoW/tbls

**Comment by AnniinaMet** [comment]
meillä on 12.4.2024 päivitetty kuva tietokantarakenteesta, joten tämä ei liene ajankohtainen enää
