### ISSUE TITLE
Selvitä mahdollisuus luoda kohteet ei-asuinrakennuksista, joissa kuitenkin asunto(ja)

### ISSUE THREAD

**Issue by ltalve** [punosmobile/jkr-lahti#128]
Huomattu, että on rakennuksia, joiden käyttötarkoitusluokka on ei-asuinrakennus, mutta joissa kuitenkin on asunto. Nykyisen määrittelyn mukaan näistä ei synny kohteita. Asunnon olemassaolo synnyttää velvoitteen, vaikka asukasta ei olisi. Koska tällaisia rakennuksia on huomattava määrä, selvitetään, onko esim. DVV-aineiston päivityksen jälkeen mahdollista luoda kohteita myös ei-asuinrakennuksista, joissa asuntojen lkm > 0. Edellyttää, että rakennusten asuntojen lkm -aineisto on tuotu kantaan.

**Comment by AnniinaMet** [comment]
on ajankohtainen ja palaamme tähän asiaan muutospyynnössä
