### ISSUE TITLE
Lisää postiosoite erikoisosoitteeksi, jos sellainen olemassa kotimaanosoitteen lisäksi

### ISSUE THREAD

**Issue by ltalve** [punosmobile/jkr-lahti#32]

**Comment by ltalve** [comment]
Myös vainajalla voi olla sekä kotiosoite että postiosoite.

**Comment by AnniinaMet** [comment]
saattaa olla tarpeen jatkokehitysvaiheessa, mutta asia voidaan tuolloin ottaa uudelleen esiin

**Comment by tero-punos** [comment]
Siirretty Jira
