### ISSUE TITLE
Viemäriverkostoaineiston kohdennus

### ISSUE THREAD

**Issue by ltalve** [punosmobile/jkr-lahti#35]
Saadaan jätevedenpuhdistamoilta/kunnilta Excel-tiedostoina. Jätehuolto muokkaa aineiston manuaalisesti.

Malliaineisto olemassa.

**Comment by ltalve** [comment]
RS 17.11.2022: Viemäriverkostotietoa tarvitaan, jotta saadaan selville kiinteistöt joiden olisi tullut tilata sako- tai umpisäiliölietteen tyhjennys. Ne kiinteistöt, jotka kuuluvat viemäriverkostoon jätetään seurannan ulkopuolelle, koska heillä lietteen käsittely on kunnossa. Jätehuolto saa viemäriverkostotiedot kunnilta tai jätevedenpuhdistamoilta. Tieto ei ole yhdenmukaista, vaan kertyy monesta lähteestä. Jätehuolto etsii tietoihin pysyvät rakennustunnukset. Näkisin, että viemäriverkostotieto olisi rakennuksen ominaisuustieto. DVV:n tiedoissa oleva viemäritieto ei ole luotettavaa, joten sitä tietoa emme käytä. Rakennukset- kohteen atribuuteissa on kenttä "onko_viemäri", pohditaan yhdessä voisiko sitä kenttää käyttää tälle tiedolle tai mikä olisi ratkaisu.

**Comment by AnniinaMet** [comment]
Tullee ajankohtaiseksi 2025
