### ISSUE TITLE
T03 Lietejätteen rekisterivelvoitteen täyttäminen

### ISSUE THREAD

**Issue by ltalve** [punosmobile/jkr-lahti#41]
**Haluan viedä lietejätteestä rekisteriin jäteasetuksessa määrittelyt tiedot, jotta noudatan jätelakia (jätelaki 39.3 §). Kuljetustieto tulee löytyä alkuperäisessä muodossa mahdollisine virheineen ja se tulee olla mahdollista ottaa ulos excel-raporttina.**

Jäteasetus 42§: 
1) kiinteistön haltijan nimi ja yhteystiedot sekä kiinteistön osoite ja kiinteistö- tai rakennustunnus;
2) tieto lietesäiliön tyypistä ja säiliön tyhjennyspäivämäärät, jos kysymyksessä on saostus- ja umpisäiliölietteen kuljetus

**Comment by AnniinaMet** [comment]
ajankohtainen 2025
