### ISSUE TITLE
T04 Biojätteen rekisterivelvoitteen täyttäminen

### ISSUE THREAD

**Issue by ltalve** [punosmobile/jkr-lahti#42]
**Haluan viedä jäteasetuksessa määritellyt tiedot rekisteriin, jotta noudatan jätelakia (jätelaki 41.2 §).**

Jäteasetus 43§: 
Jätteen haltijan on annettava jätelain 41 a §:n 2 momentissa tarkoitetusta pienimuotoisesta biojätteen käsittelystä kiinteistöllä kunnan jätehuoltoviranomaiselle vähintään seuraavat tiedot:

1) kiinteistön haltijan nimi ja yhteystiedot sekä kiinteistön osoite ja mahdollisuuksien mukaan kiinteistö- tai rakennustunnus;
2) rakennuksen tyyppi ja asuinhuoneistojen lukumäärä muusta kuin omakotitalosta;
3) jätteen käsittelystä vastaavan henkilön nimi ja yhteystiedot;
4) käsittelylaitteiston käyttötilavuus ja laitteiston vuotuinen käyttökuukausien määrä.

**Comment by AnniinaMet** [comment]
saa sulkea
