### ISSUE TITLE
T05 Rakennuskohtaiset kompostointitiedot SYKE:lle

### ISSUE THREAD

**Issue by ltalve** [punosmobile/jkr-lahti#43]
**Haluan raportoida rakennuskohtaiset kompostointitiedot Suomen ympäristökeskukselle, jotta ympäristökeskus voi raportoida Suomen kierrätysasteesta EU:lle. Tätä varten tarvitsen Excel-raportin kompostointi-ilmoituksista.**

**Comment by AnniinaMet** [comment]
saa sulkea
