### ISSUE TITLE
T08 Taustakartat käyttöliittymään

### ISSUE THREAD

**Issue by ltalve** [punosmobile/jkr-lahti#46]
**Haluan kartalle taustavaihtoehdoiksi satelliittikuvan, pohjavesikartan ja street view:n ja erilliskeräysvelvoitealueet, jotta minun ei tarvitse mennä erikseen googleen. Tarvitsen tiedon, jotta voin tehdä hakijalle päätöksen.**

**Comment by AnniinaMet** [comment]
ei toteudu vielä, mutta on toteutettavien listalla
