### ISSUE TITLE
T09 Kohteen voimassaolevat päätökset ja ilmoitukset kartalla

### ISSUE THREAD

**Issue by ltalve** [punosmobile/jkr-lahti#47]
**Haluan nähdä karttatasona voimassaolevat päätöslajit ja ilmoitukset (kompostointi, perusmaksu myönteinen, akp myönteinen, keskeytys myönteinen) per kohde. Tarvitsen tiedon, jotta näen esimerkiksi millä kohteilla on keskeytys tai missä kompostoivat kiinteistöt sijaitsevat.**

**Comment by AnniinaMet** [comment]
Ei toteudu vielä ainakaan kompostoijat haluttanee jollakin aikavälillä omaksi karttatasokseen samoin kuin vapautetut ja keskeytetyt
