### ISSUE TITLE
T10 Kuljetustiedot karttatasoilla per jätelaji

### ISSUE THREAD

**Issue by ltalve** [punosmobile/jkr-lahti#48]
**Haluan nähdä karttatason kohteen viimeisimmistä kuljetustiedoista jätelajitiedon (seka, bio, kartonki, muovi, lasi, metalli, aluekeräyspiste) per kohde.  (Haluan myös voida rajata kartalla näkyviä kohteita millä tahansa kohteen ja/tai kuljetusten ominaisuustiedolla.)**

Haluan esimerkiksi nähdä millä alueella on akp-kohteet ja välittää tiedon sekä käydä keskustelua jäteyhtiön kanssa akp-asiakkaista ja tulisiko akp-keräyspaikkojen paikkoja miettiä uudelleen, tämän asia toisi lisävalaistusta myös Palvelutason määrittelyyn.
Haluan nähdä missä on vapaaehtoista biojätteen keräystä, jotta voisi miettiä velvoitteiden kiristämistä.

**Comment by AnniinaMet** [comment]
ratkaistu
