### ISSUE TITLE
T12 Lietteen velvoitteiden täyttyminen kartalla

### ISSUE THREAD

**Issue by ltalve** [punosmobile/jkr-lahti#51]
**Haluan nähdä lietteen velvoitteen täyttymisen (liikennevalomalli) kartalla väreinä, jotta näen kohteen yleistilanteen ensisilmäyksellä. Tarvitsen tiedon, jotta näen kohteen tai alueen kohteiden velvoitteiden täyttymisen yhdellä silmäyksellä tai esittelen tilannetta sidosryhmälle. Lisäksi voin havainnoida onko jollakin maantieteellisellä alueella ongelmia, joihin voisi viestinnällisesti keskittyä.**

Karttataso liikennevalot liete: Kaikki kohteen rakennukset on saman värisiä.

![Image](https://user-images.githubusercontent.com/83061576/212891997-af29ff7a-5974-46f1-a872-6ddb2bc358ba.png)

**Comment by AnniinaMet** [comment]
tullee ajankohtaiseksi 2025
