### ISSUE TITLE
T14 Excel-raportti kohteiden velvoitteiden täyttymisestä

### ISSUE THREAD

**Issue by ltalve** [punosmobile/jkr-lahti#53]
**Haluan ottaa itse excel-raportin jätehuoltovelvoitteiden täyttymisestä kohteittain. Tarvitsen raportin, jotta voin laskea jätehuoltoon liittymisprosentteja tai muita tunnuslukuja ei visuaaliseen raportointiin. Raportti tulee saada kohteittain.**

Kohteen rivitiedoissa ovat mukana ne kohdetta koskevat kuljetustiedot, päätöstiedot, ilmoitustiedot, ominaisuustiedot (kuntaurakka, taajama/haja, viemäriverkostotieto) ja ne dvv-aineistosta tulevat tiedot, joita olen käyttänyt hakuehtoina . Raportille tarvitsen esimerkiksi seuraavat tiedot: kohdeid, kohteen rakennusten PRT, velvoitteen täyttyminen, kuntaurakka-alue/kiinteistönhaltijan alue, taajama-alue vai muu alue, kohteen rakennusten käyttötarkoituksen, kohteen rakennuksen käyttötila, osoite, kuntatunnus.

Yksi rivi/kohde.

**Comment by AnniinaMet** [comment]
saa sulkea
