### ISSUE TITLE
T15+16 Muut Excel-raportit käyttöliittymästä

### ISSUE THREAD

**Issue by ltalve** [punosmobile/jkr-lahti#54]
**Haluan ottaa Excel-raportin itse liittymästä, koska raporttien tarvetta on vaikea ennakoida. Näitä en tarvitse kartalle.** 

Haluan itse valita mitä tietoja otan raportille ja miten rajaan raportin
1) ajallisesti (esim. kuljetustietojen raportointijakso) 
2) alueellisesti (esim. kunta/postinumero).

- Tietopyyntö ks. T1 (#39)
- Haluan raportoida kompostointitiedot ks. T5 (#43). Tarvitsen tiedon myös, kun haluan vastata jäteyhtiön tietopyyntöön biojätteen kotinoutopalveluun kuuluvien kohteiden selvittämiseksi.
- Velvoiteraportti ks. T14 (#52)
- Velvoitteiden täyttyminen liikennevalomalli ks. T14 (#52).
- Päätökset ja ilmoitukset: Esim. voimassa olevat myönteiset voimassaolevat perusmaksun poistopäätökset, keskeytykset ja myönteiset akp-kohtuullistamiset. (Tästä näen ne joilla ei tarvitse olla jätteenkuljetusta.)
- Kohteet, joilla joku tietty yksittäinen velvoite ei täyty, ei liikennevalomallitapaus. Voin olla kerralla yhteydessä kaikkiin, joilta puuttuu esimerkiksi muoviastia.

Haluan raportteja kohteista. Kohteen rivitiedoissa ovat mukana ne kohdetta koskevat kuljetustiedot, päätöstiedot, ilmoitustiedot, ominaisuustiedot (kuntaurakka, taajama/haja, viemäriverkostotieto) ja ne dvv-aineistosta tulevat tiedot, joita olen käyttänyt hakuehtoina. 

Esimerkkejä:

- Velvoitteiden täyttyminen liikennevalomalli ks. kohta 15 (#53).
- Päätökset ja ilmoitukset. Haluan tiedon esimerkiksi, jos vastaan jäteyhtiön tietopyyntöön biojätteen kotinoutopalveluun kuuluvien kohteiden selvittämiseksi.
- Kohteet, joilla joku tietty yksittäinen velvoite ei täyty, ei liikennevalomallitapaus. Saan tiedon puuttuvista jäteastioista kohteittain.
- Haluan saada raportin kohteista, jotka on kuljetustietojen perusteella kimpassa keskenään. Tällä pystyn seuraamaan, onko kimppaehtoihin tarpeen tehdä muutoksia.

**Comment by ltalve** [comment]
Tarinassa tällä hetkellä kaatoluokkana paljon erilaisia raportteja (yhdistettynä tarinat 16 ja 17).

**Comment by AnniinaMet** [comment]
raporttipohjia tullaan tarvitsemaan lisää, nykyisen yhden raporttipohjan lisäksi.
