### ISSUE TITLE
T20 Lietekuljetustietojen päivitys

### ISSUE THREAD

**Issue by ltalve** [punosmobile/jkr-lahti#58]
**Haluan viedä lietekuljetusten tiedot neljännesvuosittain, jotta lakisääteinen jätehuollon kuljetusrekisterinpitovelvoite täyttyy jätehuollon seurantaa voidaan tehdä riittävän ajantasaisesti. Tietojen viemiseksi tietokantaan tulee olla työkalu tai ohjeistettu toimintamalli.**

**Comment by ltalve** [comment]
V.2023 alusta lähtien saostus- ja umpisäiliölietteiden kuljettaja voi korvata SIIRTO-rekisteriin toimitetuilla tiedoilla jätelaissa säädetyn velvollisuutensa antaa kunnan jätehuoltoviranomaisille neljännesvuosittain tiedot kiinteistöistä, joilta lietettä on noudettu ja säiliöiden tyhjennyskerroista, jätteen määrästä ja toimituspaikoista. Arvio, että malliaineisto saatavilla 12/2022.

**Comment by AnniinaMet** [comment]
Tulee ejankohtaiseksi 2025
