### ISSUE TITLE
T23 Viemäriverkostoaineiston päivitys

### ISSUE THREAD

**Issue by ltalve** [punosmobile/jkr-lahti#61]
**Haluan päivittää viemäriverkostoaineiston itse (rakennuksen PRT) vuosittain, jotta jätehuollon seurantaa voidaan tehdä riittävän ajantasaisesti. Tietojen viemiseksi tietokantaan tulee olla työkalu tai ohjeistettu toimintamalli.**

- [ ] #35

**Comment by AnniinaMet** [comment]
Tullee ajankohtaiseksi 2025
