### ISSUE TITLE
T25 Taajamarajauksen päivitys

### ISSUE THREAD

**Issue by ltalve** [punosmobile/jkr-lahti#63]
**Haluan tarvittaessa päivittää erilliskeräysrajauksen (taajamarajaus)**

Taajamarajauksen muututtua käytettävänä on uusi shp-tiedosto, joka pitää ajaa kantaan.

- [x] #37

**Comment by ltalve** [comment]
17.3.2023 projektipäälliköiden palaverissa mainittu, että päivityksen tarvetta on vain noin 5 vuoden välein, joten päivitys ei ehkä ole MVP:n osalta aivan välttämätön toiminnallisuus.

**Comment by AnniinaMet** [comment]
Tulee ajankohtaiseksi jossakin vaiheessa
