### ISSUE TITLE
Lisää kohteiden luonnin excel-lokitus

### ISSUE THREAD

**Issue by Rikuoja** [punosmobile/jkr-lahti#75]
Tällä hetkellä kohteiden luontityökalu lokittaa lähinnä suoraan komentoriville uudet luodut kohteet.

Tehtävä lokitus kaikista a) uusista, b) muuttuneista ja c) poistetuista kohteista dvv-päivityksen yhteydessä https://github.com/GispoCoding/jkr-lahti/issues/64, ehkä eri logiputkiin.

Jokaisen login voisi tulostaa erilliselle excel-sheetille, jota on helppo selailla ja vertailla osoitteittain kohteisiin qgisissä. Näin uusia/muuttuneita/poistettuja kohteita voi tarpeen mukaan korjata tuonnin jälkeen qgisissä manuaalisesti.

Päätettävä mitä kaikkea jokaiselle logiriville lisätään. Mikä on paras tapa esittää kohteen tiedot excelissä?
- kohteen kaikkien rakennusten prt:t ja kaikki osoitteet? Vai jokainen rakennus omalle rivilleen ja yhteinen kohde-id?
- kohteen osapuolet? Vai jokainen osapuoli omalle rivilleen ja yhteinen kohde-id?

**Comment by ltalve** [comment]
6.3. päätettiin odottaa tämän kanssa ja katsoa, josko tarvittava tieto olisi saatavissa myös tietokantahaulla erillisen lokin sijaan. Tarvittaessa lokitus voidaan toteuttaa myöhemmässä vaiheessa.

**Comment by AnniinaMet** [comment]
Lokitus tultaneen tarvitsemaan
