### ISSUE TITLE
Tarkista kohteiden luonti yhden asunnon kohteiden osalta

### ISSUE THREAD

**Issue by ltalve** [punosmobile/jkr-lahti#89]
Selvitettävä: yhden asunnon kohteita luotaessa näyttää syntyvän myös joitakin kohteita, joilla on useampi rakennus. Saattaa johtua siitä, että samalla osapuolella on sekä yhden asunnon kohde että muunlainen kohde, ja kaikki luodaan samalla kerralla.

**Comment by AnniinaMet** [comment]
En osaa sanoa onko edelleen ajankohtainen, kohteiden luontiin ollaan joka tapauksessa tekemässä muutoksia, joten tämä kannattanee siinä huomioida
