### ISSUE TITLE
Päivitystyökalun dokumentaation päivitys uuden version jaon yhteydessä.

### ISSUE THREAD

**Issue by Mtk112** [punosmobile/jkr-lahti#93]
Päivitä JKR-wheelin dokumentaatio, kun uusi versio laitetaan jakoon.
Rakenne muuttunut:
Zipatut .sql- ja .bat-tiedostot omaan scripts-kansioon.
Selvennä miten .bat-tiedosto saadaan avattua esim. muistiolla.

**Comment by AnniinaMet** [comment]
Päivitystyökalun dokumentaatio tulee totta kai päivittää aina kun työkaluun tulee muutksia, mutta käsitykseni mukaan dokumentaatio on ajantasalla, ainakin siltä osin kun se loppukäyttäjälle on nähtävissä.
